name: Build Moonlight

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build app
        run: |
          xcodebuild \
            -workspace Moonlight.xcworkspace \
            -scheme Moonlight \
            -configuration Debug \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO